= How to write and change the functional documentation

Here is defined and described what you have to do when you add a new feature (e.g.: functional or non-functional requirement) to the JUDO ecosystem, or you modify also existing feature.

== How to add a new feature or requirement

This section describes how you can add new feature to the JUDO framework. This may be an addition function into an existing domain (e.g.: adding a new string function: trim), or a totally new feature domain (e.g.: transfer objects). In the first case enough xref:#newsection[to modify an existing adoc file], and the second case you necessary xref:#newadoc[to add a new adoc file].

[#newadoc]
=== Adding new adoc file

If you add a new functional definition document (*.adoc), you need to add a _judo-reqprefix_ document attribute (metadata) to the adoc file. It is a short character string, which will be used in the unique identifier generation, therefore it must be unique in the JUDO project.

.Using "judo-reqprefix" attribute
[source,adoc]
----
:judo-reqprefix: REQ-FNC

= Title of document

----

The current naming convention is to start with "REQ-" and it follows by 3-4 upper case characters, which are together creating an abbreviation or acronym that refers the function set.

==== Checking the uniqueness of the judo-reqprefix.

TODO: JNG-4364

[#newsection]
=== Adding new section into an existing adoc document

If you create a new section in an existing or new functional requirement document, that is defines a requirement or a behaviour, you need to add an extra _judo-requirement_ or _judo-req_ boolean type attribute to the header of the sections.

[source,adoc]
----
[judo-req="true"]
== Func1

...

[judo-req="true"]
== Func2

[judo-requirement="true"]
=== Req1 of Func2

...

[judo-req="true"]
=== Req2 of Func2

...

----

When you finish the function description you have to implement it, and xref:#testcases[to define and to write the necessary test cases].

== How to change a document section

If you changed any existing feature / requirement you have a little additional tasks. Update the related test cases or add new test cases if necessary. See the xref:#testcases[Update test cases]

[#testcases]
== Update the test

If you have modified any requirement you will need to update the related test cases, or add new test cases. See the xref:02-how_to_write_tests.adoc[How to write tests] document for the practical details.