= How to write and change the functional documentation

Here is defined and described what you have to do when you add a new feature to the JUDO ecosystem, or you modify also existing feature.

== How to add new section

=== Adding new adoc file

If you add a new functional definition document (*.adoc), you need to add a _judo-reqprefix_ document attribute (metadata) to the adoc file. It is a short character string, which will be used in the unique identifier generation, therefore it must be unique in the JUDO project.

.Using "judo-reqprefix" attribute
[source,adoc]
----
:judo-reqprefix: REQ-FNC

= Title of document

----

==== Check the uniqueness of the prefix.

TODO

[#newsection]
=== Adding new section into an adoc document

If you create a new section in an existing or new functional requirement document, that is defines a requirement or a behaviour, you need to add an extra _judo-requirement_ or _judo-req_ boolean type attribute to the header of the sections.

[source,adoc]
----
[judo-req="true"]
== Func1

...

[judo-req="true"]
== Func2

[judo-requirement="true"]
=== Req1 of Func2

...

[judo-req="true"]
=== Req2 of Func2

...

----

== How to change a document section

TODO
