= How to write and change the functional documentation

Here is defined and described what you have to do when you add a new feature to the JUDO ecosystem, or you modify also existing feature.

== How to add new section

=== Adding new adoc file

If you add a new functional definition document (*.adoc), you need to add a _reqprefix_ document attribute to the adoc file. It is a short character string, which will be used in the unique identifier generation, therefore it must be unique in the JUDO project.

.Using "reqprefix" attribute
[source,adoc]
----
:reqprefix: REQ-FNC

= Title of document

----

==== Check the uniqueness of the prefix.

TODO

[#newsection]
=== Adding new section into an adoc document

If you create a new section in an existing or new functional requirement document, that is defines a requirement or a behaviour, you need to add an extra _requirement_ or _req_ attribute to the header of the sections.

[source,adoc]
----
[requirment]
== Func1

...

[req]
== Func2

[requirement]
=== Req1 of Func2

...

[req]
=== Req2 of Func2

...

----

== How to change a document section

TODO
