= How to write tests

Here is defined and described what is the test writing methodology. If you add a new test, you have to follow these directions.

== Create new test case

When you create a test case method, the first thing that you have to do is that to identify which requirement(s) want to test. If you identified it, you have to attach this information as an annotation to the test method. See en example:

[source,java]
----
@Requirement(reqs = {
        "REQ-ENT-004",
        "REQ-ENT-005",
        "REQ-EXPR-003"
})
public void test() {
...
}
----

As you can see, you can attach more than one requirement identifier. Most cases you have to apply when you write a unit test.

When you implement a test definition, you have to attach the Test Definition Identifier to the test method. In this case you can also do it an annotation that name is TestDefinition. See an example:

[source,java]
----
@TestDefinition(testDefs = {
        "TCD001",
        "TCD002"
})
public void test() {
...
}
----

== Modify an existing test case

TODO