name: Full integration release on develop
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
jobs:
  build:
    runs-on: judong
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Checkout submodules using a PAT
        run: |
          git config --file .gitmodules --get-regexp url | while read url; do
            git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.OSS_PAT }}:${{ secrets.OSS_PAT }}@github.com\//")
          done
          git submodule sync
          git reset --hard
          git submodule foreach --recursive 'git reset HEAD . || :'
          git submodule foreach --recursive 'git checkout -- . || :'
          git submodule update --init --recursive
          git clean -d -f -x
          git submodule foreach --recursive git clean -d -f -x
          git submodule update --init --recursive

      - name: Project context
        id: context
        uses: zero88/gh-project-context@v1.1

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_SECRET_KEYS }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
          gpg-private-key: ${{ secrets.GPG_SECRET_KEYS }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Remove settings.xml
        run: rm $HOME/.m2/settings.xml || true
          
      - name: Setup maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: >
            [
                {
                    "id": "judong-nexus-mirror",
                    "username": "${{ secrets.JUDONG_NEXUS_USERNAME }}",
                    "password": "${{ secrets.JUDONG_NEXUS_PASSWORD }}"
                },
                {
                    "id": "judong-nexus-distribution",
                    "username": "${{ secrets.JUDONG_NEXUS_USERNAME }}",
                    "password": "${{ secrets.JUDONG_NEXUS_PASSWORD }}"
                }
            ]

          mirrors: >
            [
                {
                    "id": "judong-nexus-mirror",
                    "mirrorOf": "*",
                    "url": "https://nexus.judo.technology/repository/maven-judong/"
                 }
            ]

      - name: Print settings.xml
        run: cat $HOME/.m2/settings.xml

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.10
          architecture: x64

      - name: Install weel
        run: pip3 install wheel

      - name: Install dependencies
        run: pip3 install atlassian-python-api

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Check python
        run: python3 --version

      - name: Setup git user
        run: |
            git config --global user.name "OSS"
            git config --global user.email "oss@blackbelt.hu"

      - name: Checkout repositories
        run: python3 ./project.py -gh ${{ secrets.OSS_PAT }} -gc

      - name: Fetch versions
        run: python3 ./project.py -gh ${{ secrets.OSS_PAT }} -fv

      - name: Run integration build
        run: python3 ./project.py -gh ${{ secrets.OSS_PAT }} -ib

      - name: Create Pull Request for release into current branch
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.OSS_PAT }}
          commit-message: '[RELEASE] Release version: ${{ github.event.inputs.version }}'
          branch: release/v${{ github.event.inputs.version }}
          delete-branch: true
          title: '[RELEASE] Release version: ${{ github.event.inputs.version }} to develop'
          body: >
            This PR is auto-generated. Creates pull request develop master which contains the coresponding release's source code.
          labels: release, automated pr
